### ISSUE TITLE
Monetary intensity factor per NACE

### ISSUE THREAD

**Issue by mgalibert** [konstantinstadler/pymrio#99]
Hello, I read and installed with attention pymrio. It works perfectly on my mac. 
However I'm really a beginner on how such databases work overall. 
I would like to do something pretty basic: extract monetary factors (CO2e/€) for all categories/industries. My ultimate goal: calculate a monetary factor for each NACE code based on the following EXIOBASE correspondence table:
https://ntnu.app.box.com/v/EXIOBASEconcordances/file/682195219009
Is there anyway to do this easily?
Many thanks for your help

**Comment by konstantinstadler** [comment]
Hi

Hi,

EXIOBASE and IO nomenclature in general can be tricky. There is no actual standard (yet), we tried to follow the most common abbreviations.

So the names are given in the description text at Zenodo ( https://doi.org/10.5281/zenodo.3583070 - section "Content of IOT*.zip").

For the meaning of the names, I put together some table in the pymrio documentation: https://pymrio.readthedocs.io/en/latest/terminology.html

Depending on the EXIOBASE version, M might already be included, otherwise you can calulate it with pymrio with calc_all after parsing exiobasee  - the documentation should cover these cases.

best
kst
________________________________
From: mgalibert ***@***.***>
Sent: Monday, February 6, 2023 12:45
To: konstantinstadler/pymrio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [konstantinstadler/pymrio] Monetary intensity factor per NACE (Issue #99)


Hello, I read and installed with attention pymrio. It works perfectly on my mac.
However I'm really a beginner on how such databases work overall.
I would like to do something pretty basic: extract monetary factors (CO2e/€) for all categories/industries. My ultimate goal: calculate a monetary factor for each NACE code based on the following EXIOBASE correspondence table:
https://ntnu.app.box.com/v/EXIOBASEconcordances/file/682195219009
Is there anyway to do this easily?
Many thanks for your help

**Comment by mgalibert** [comment]
Thanks for your answer, I'll look into it.
